server:
  port: 8080
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: ms-after-sales
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sh-cdb-42xoavqj.sql.tencentcdb.com:63280/db_janus?characterEncoding=utf8
    username: janus
    password: janus123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    max-idle: 5
    min-idle: 5
    initial-size: 5
    max-wait: 10000
  webflux:
    static-path-pattern: /**
spring.resources.static-locations: classpath:/static/dist
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.clsaa.ms.hermes.entity.po
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: true  #返回JSON统一日期为时间戳
spring.jackson.serialization.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

janus:
  app:
    auth:
      aesKey: #应用相关的AesKey
        AccessKey: 123456class654321 #用于加密AccessKey的密匙
        AccessSecret: 123456class654321   #用于加密AccessSecret的密匙
  service:
    auth:
      aesKey: #后端服务相关的AesKey
        AccessKey: 123456class654321 #用于加密AccessKey的密匙
        AccessSecret: 123456class654321   #用于加密AccessSecret的密匙